spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5436}/${DB_NAME:auditdb}
    username: ${DB_USER:audit}
    password: ${DB_PASSWORD:audit}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${PORT:8084}

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /swagger

app:
  security:
    jwt:
      issuer: ${JWT_ISSUER:ledgerpay}
      secret: ${JWT_SECRET:dev-secret-change}
      access-token-ttl: PT15M

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
