services:
  auth-service:
    build: ./services/auth-service
    environment:
      PORT: 8080
      JWT_ISSUER: ledgerpay
      APP_SECURITY_JWT_SECRET: this_is_a_development_jwt_secret_that_is_long_enough_please_change_in_prod_1234567890
    ports:
      - "8090:8080"
    restart: on-failure
  accountsdb:
    image: postgres:16
    environment:
      POSTGRES_DB: accountsdb
      POSTGRES_USER: accounts
      POSTGRES_PASSWORD: accounts
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U accounts -d accountsdb"]
      interval: 5s
      retries: 10
  accounts-service:
    build: ./services/accounts-service
    environment:
      DB_HOST: accountsdb
      DB_PORT: 5432
      DB_NAME: accountsdb
      DB_USER: accounts
      DB_PASSWORD: accounts
      PORT: 8081
      SPRING_PROFILES_ACTIVE: dev
      APP_SECURITY_JWT_SECRET: this_is_a_development_jwt_secret_that_is_long_enough_please_change_in_prod_1234567890
      JWT_SECRET: this_is_a_development_jwt_secret_that_is_long_enough_please_change_in_prod_1234567890
    restart: on-failure
    depends_on:
      accountsdb:
        condition: service_healthy
    ports:
      - "8081:8081"

  postingdb:
    image: postgres:16
    environment:
      POSTGRES_DB: postingdb
      POSTGRES_USER: posting
      POSTGRES_PASSWORD: posting
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U posting -d postingdb"]
      interval: 5s
      retries: 10
  posting-service:
    build: ./services/posting-service
    environment:
      DB_HOST: postingdb
      DB_PORT: 5432
      DB_NAME: postingdb
      DB_USER: posting
      DB_PASSWORD: posting
      PORT: 8082
      SPRING_PROFILES_ACTIVE: dev
      APP_SECURITY_JWT_SECRET: this_is_a_development_jwt_secret_that_is_long_enough_please_change_in_prod_1234567890
      services.audit.url: http://audit-service:8084
      services.query.url: http://query-service:8083
    depends_on:
      postingdb:
        condition: service_healthy
      audit-service:
        condition: service_started
    ports:
      - "8082:8082"
    restart: on-failure

  querydb:
    image: postgres:16
    environment:
      POSTGRES_DB: querydb
      POSTGRES_USER: query
      POSTGRES_PASSWORD: query
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U query -d querydb"]
      interval: 5s
      retries: 10
  query-service:
    build: ./services/query-service
    environment:
      DB_HOST: querydb
      DB_PORT: 5432
      DB_NAME: querydb
      DB_USER: query
      DB_PASSWORD: query
      PORT: 8083
      SPRING_PROFILES_ACTIVE: dev
      APP_SECURITY_JWT_SECRET: this_is_a_development_jwt_secret_that_is_long_enough_please_change_in_prod_1234567890
      POSTING_URL: http://posting-service:8082
    depends_on:
      querydb:
        condition: service_healthy
    ports:
      - "8083:8083"
    restart: on-failure

  auditdb:
    image: postgres:16
    environment:
      POSTGRES_DB: auditdb
      POSTGRES_USER: audit
      POSTGRES_PASSWORD: audit
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audit -d auditdb"]
      interval: 5s
      retries: 10
  audit-service:
    build: ./services/audit-service
    environment:
      DB_HOST: auditdb
      DB_PORT: 5432
      DB_NAME: auditdb
      DB_USER: audit
      DB_PASSWORD: audit
      PORT: 8084
      SPRING_PROFILES_ACTIVE: dev
      APP_SECURITY_JWT_SECRET: this_is_a_development_jwt_secret_that_is_long_enough_please_change_in_prod_1234567890
    depends_on:
      auditdb:
        condition: service_healthy
    ports:
      - "8084:8084"
    restart: on-failure
