server:
  port: ${PORT:8080}

app:
  security:
    jwt:
      issuer: ${JWT_ISSUER:ledgerpay}
      secret: ${APP_SECURITY_JWT_SECRET:dev-secret-change}
      access-token-ttl: PT15M

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /swagger
