spring:
  application:
    name: query-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:querydb}
    username: ${DB_USER:query}
    password: ${DB_PASSWORD:query}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${APP_SECURITY_JWT_SECRET:this_is_a_development_jwt_secret_that_is_long_enough_please_change_in_prod_1234567890}

server:
  port: ${PORT:8083}

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /swagger

app:
  security:
    jwt:
      issuer: ${JWT_ISSUER:ledgerpay}
      secret: ${JWT_SECRET:dev-secret-change}
      access-token-ttl: PT15M

services:
  posting:
    url: ${POSTING_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      probes:
        enabled: true
