server:
  port: 8083

spring:
  application:
    name: query-service
  datasource:
    url: jdbc:postgresql://querydb:5432/querydb
    username: query
    password: query
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,swagger-ui
  endpoint:
    health:
      show-details: always

# JWT Configuration
app:
  security:
    jwt:
      secret: ${APP_SECURITY_JWT_SECRET:default_dev_secret_key_at_least_256_bits_long_for_security}
      issuer: ${JWT_ISSUER:ledgerpay}
      access-token-ttl: PT1H

# Logging
logging:
  level:
    com.ledgerpay: DEBUG
    org.springframework.web: DEBUG
